1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
import numpy as np
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [5]:
import numpy as np
vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
arr = np.array([1,2,0,0,4,0])
non_zero_indices= np.nonzero(arr)[0]
print(non_zero_indices)


[0 1 4]


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
arr1 = np.random.randint(1,50,(10,10))
print("THE ARRAY IS", arr1)
print("THE MINIMUM VALUE IN ARRAY IS", np.min(arr1))
print("THE MAXIMUM VALUE IN ARRAY IS", np.max(arr1))

THE ARRAY IS [[ 7 24  3 49 35 41  7 46 22 30]
 [17 16 30 18 44 45 46 46 39 27]
 [26 45 49 31 17 23 40 19 12 35]
 [17  7 24 14 40 22 13 14  4  6]
 [32 34 49 33  2 16 28 37 21 10]
 [37 42 30 21 11 24 19 42 11 38]
 [38 41 36  5 17 42  8 15 44 36]
 [ 6 25  4 15 40 18 49 17 31 46]
 [ 2 16 31 47 26  2 14 35 41 22]
 [37 47 21 38 21 19 25 37 21  9]]
THE MINIMUM VALUE IN ARRAY IS 2
THE MAXIMUM VALUE IN ARRAY IS 49


6. Create a random vector of size 30 and find the mean value.

In [15]:
vec= np.random.rand(30)
print("THE REQUIRED VECTOR IS", vec)
print("\n\nTHE MEAN OF VECTOR IS", np.mean(vec))

THE REQUIRED VECTOR IS [0.88621179 0.76480991 0.2151732  0.71749471 0.91017669 0.83511627
 0.67751744 0.15724339 0.52445018 0.7237189  0.63801527 0.01377153
 0.58919116 0.27437248 0.44996854 0.26205735 0.1763275  0.95037142
 0.38646423 0.10266993 0.20315644 0.87130281 0.12132856 0.61149223
 0.72692954 0.88439964 0.29544809 0.62058814 0.92717022 0.56654427]


THE MEAN OF VECTOR IS 0.5361160612150065
